
export const CONFIGURE_NEW_BOARD = "CONFIGURE_NEW_BOARD";
export const TOGGLE_SHOW_GAME = "TOGGLE_SHOW_GAME";
export const REVEAL_CELL = "REVEAL_CELL";
export const FLAG_CELL = "FLAG_CELL";
export const UNFLAG_CELL = "UNFLAG_CELL";
export const INCREMENT_TIME = "INCREMENT_TIME";
export const START_CLOCK = "START_CLOCK";
export const RESTART_BOARD = "RESTART_BOARD";
export const CHANGE_TO_EASY = "CHANGE_TO_EASY";
export const CHANGE_TO_MEDIUM = "CHANGE_TO_MEDIUM";
export const CHANGE_TO_HARD = "CHANGE_TO_HARD";
